### ISSUE TITLE
Optimize cpp2doc

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#101]
As we are re-adding it, it would be nice to optimize it a bit:
- run a profiler, maybe there's something that could be optimized
- check if the md file timestamp is later than the cpp one, and if so do not update the documentation for this particular C++ file.

See #59 for discussion on the documentation generation.

**Comment by dfaure-kdab** [comment]
$ rm -f ../docs/API/knut/*.md ; time bin/cpp2doc
bin/cpp2doc  0,07s user 0,00s system 99% cpu 0,077 total

Not sure there's much room for optimization there, it's really fast, isn't it?
