### ISSUE TITLE
Check symbols creation for C++

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#117]
Make sure the symbols created by `symbols()` make sense, particularly that the types are good.
I *think* at least the members have an empty type.

**Comment by LeonMatthesKDAB** [comment]
So at the moment the symbols themselves are of *kind* Field.
This just resolves to an instance of `Symbol`, which only knows about things like `range` and `selectionRange`.

And adding a general `type` field to that probably doesn't make sense.
As not all Symbols have a type (e.g. what "type" does a "Constructor", or an "Operator" have?)

But maybe adding a subclass "TypedSymbol" makes sense, which could know about the type.
I'll try adding that.
