### ISSUE TITLE
Add a way to display log in a ScriptDialog

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#26]
Currently, scripts report their output through logging.
However, the log output doesn't render whilst the script is running.

This could be a good first step to indicate how far along a script is and to show the user that it's indeed doing something.

We could imagine adding a `QPlainTextEdit` with a particular name `LogOutput` or something like that. In the `ScriptDialogItem`, if we find such `QPlainTextEdit`, we initalize it in readonly log mode, and redirect the logging output to it.
Hint: there's a small syntaxhilighting in GUI that could be used, see `LogHighlighter`

**Comment by LeonMatthesKDAB** [comment]
How exactly would this solve our issue? We already have a Log panel.

The issue is that the Log panel isn't updated while JS code runs, as that is single-threaded, right?
But any other UI item, like the mentioned QPlainTextEdit, also won't update, so what would be different here?

**Comment by narnaud** [comment]
The logs are displayed when running a script in the GUI, and visible from the Log panel (we should probably remove them from the history though... another task).

The problem this task is trying to fix is when using knut via the command line: you don't see any logs. For example, when doing the rc to ui conversion, there are some warnings displayed when a flag is not handled, but I'm missing them.

So the idea is to have a way to add a `QPlainTextEdit` inside the script ui that displays the log.
Hope it's clearer.

**Comment by LeonMatthesKDAB** [comment]
Ah, okay. That's clearer.

Shouldn't the command line output just print everything that we dump out with spdlog?

Or do you mean if you don't have a terminal open at all but still run it in script mode?

**Comment by narnaud** [comment]
Unfortunately, it doesn't work on Windows, we can't see the command line output... (limitation of Windows, a GUI program does not display anything when run from the CLI).
The nice thing is that it will also work for people running it from another IDE (like Visual Studio, QtC...)

**Comment by LeonMatthesKDAB** [comment]
Okay, then that clarifies it :+1:
