### ISSUE TITLE
Macros can break Tree-Sitter parsing

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#30]
Example:
```
class AFX_EXT_CLASS CPrjDbase6 : public CDialog
{}; 
```
 
This is parsed entirely incorrectly:
![image-2024-03-01-10-46-55-138](https://github.com/KDAB/knut/assets/469305/14dc1d02-9503-4674-821e-135f425130ad)

It's a known bug in tree-sitter-cpp, that doesn't seem to have an easy solution.
https://github.com/tree-sitter/tree-sitter-cpp/issues/85

It would be good to be able to fix this from within Knut somehow.

**Comment by narnaud** [comment]
That was my idea too: remove everything that is between `class  XXXXX  Word:` using a regexp, and re-adding after the script.
It will need to be done explicitely though, as I don't think we could do that for the user.

Something along those lines:
```
headerDocument.cleanExport()
..
..
..
headerDocument.restoreExport()
```

It's not really fixing the issue, but workarounding it :)

**Comment by LeonMatthesKDAB** [comment]
Ah, hm, I was thinking that we can just remove the macro when we're porting to e.g. Qt.
But of course you may want to run a script that doesn't do a full transform, so it would be no use there. Tricky :thinking:

**Comment by narnaud** [comment]
You can't remove the export macro as you still need it on Windows, even with Qt.
As a first step, to mitigate the issue, we could warn people when we detect an export macro (should be easy with a small regexp). A `spdlog::warning` or even `spdlog::error` when using API that breaks due to that (symbol / queryClass/queryMember).

That would be an acceptable fix for v1.

**Comment by LeonMatthesKDAB** [comment]
New idea: We can actually include/exclude certain ranges from the parsing.
See: https://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents
For many macros it should be enough to just skip them during parsing, so let's try that.
We could then even add them back as a custom TSLanguage if we wanted to.

**Comment by LeonMatthesKDAB** [comment]
TODO: Put the macros to filter out in a setting. We may need to create a `CppSettings` subclass for this.
