### ISSUE TITLE
Remove Knut.Test all together

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#49]
We don't need that anymore, there's a TestCase directly in Qt using QTest:
https://doc.qt.io/qt-6/qml-qttest-testcase.html

- [ ] refactor the test-data/tst_*.qml to use QTest
- [ ] move the static methods from core/TestUtil to test_utils.h (they are not used anymore in the QML files
- [ ] remove TestUtil and TestCase.qml from core

**Comment by LeonMatthesKDAB** [comment]
Abandon for now, as explained in #96
