### ISSUE TITLE
Simplify API documentation

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#50]
This is a follow up of #49 

Now that we only have a Script module, it doesn't really make sense to explicitly says it's in this module.

- [ ] Remove all `\inqmlmodule Script` in the code documentation
- [ ] Change cpp2doc tool to always put in the Script module if there are no `\inqmlmodule` (we want to be able to use it, just in case for later)

**Comment by narnaud** [comment]
Probably need to do #56 first, so we don't have to change the module name again.

**Comment by LeonMatthesKDAB** [comment]
Note: #56 is done now.
