### ISSUE TITLE
Better handling of revision/changelog

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#51]
In fine, we want to use release-please for doing the release. In order to do that.

We are going to use the simple strategy here: https://github.com/googleapis/release-please/blob/main/docs/customizing.md

- [x] Add a version.txt file (we can set the version to 0.1.0 for now)
- [x] Use this file text to set the version inside CMake `file(READ "version.txt" ver)`
- [x] Use the version number for the Script QML module (in scriptrunner.cpp`

**Comment by LeonMatthesKDAB** [comment]
We actually don't need to change the registration of QML types, as those need to be registered with the version they were first introduced, not the current version.

@narnaud did however come up with a cool idea to automate defining something as coming from the next release:
Maybe we can define some macros, like KNUT_NEXT_VERSION that we can string-replace using release-please to always point to the next version number.

Then we could e.g. write
```
\since KNUT_NEXT_VERSION
```
In our documentation and have that automatically replaced on the next release PR by e.g.
```
\since 1.1
```
This is something to try when setting up release-please as part of #3 .

**Comment by LeonMatthesKDAB** [comment]
Done as of #57
