### ISSUE TITLE
QML: Rename `Scripts` module

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/knut#56]
The `Scripts` name is somewhat nondescript.

We should rename this to `Knut`, or `com.kdab.knut` before releasing v1.0.
The exact name still needs to be chosen.

**Comment by narnaud** [comment]
I would prefer `import Knut`

Also take this opportunity to remove all version numbers in QML/JS
That's the new way to do things in Qt, so just `import Knut`, not `import Knut 1.0`
