### ISSUE TITLE
Improve nextStep API in ScriptDialog

### ISSUE THREAD

**Issue by narnaud** [KDAB/knut#72]
The `nextStep` API is good for big independent steps, but bad showing progress of one action (for example, the same action being done on 1000 items).

It would be good to improve the API:
- if the string is empty (ie calling `nextStep()`), then repeat the previous string
- don't update more than 5x times per seconds (meaning you need a timer to do the update).

Would be good to have some numbers to see how it impacts script with a before/after.

**Comment by smnppKDAB** [comment]
Fix in the PR#129
